//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxAsyncConsole.AsyncWorkerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsyncWorkerServiceReference.IAsyncWorkerService")]
    public interface IAsyncWorkerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncWorkerService/GetData1", ReplyAction="http://tempuri.org/IAsyncWorkerService/GetData1Response")]
        int GetData1();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAsyncWorkerService/GetData1", ReplyAction="http://tempuri.org/IAsyncWorkerService/GetData1Response")]
        System.IAsyncResult BeginGetData1(System.AsyncCallback callback, object asyncState);
        
        int EndGetData1(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncWorkerService/GetData2", ReplyAction="http://tempuri.org/IAsyncWorkerService/GetData2Response")]
        int GetData2();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAsyncWorkerService/GetData2", ReplyAction="http://tempuri.org/IAsyncWorkerService/GetData2Response")]
        System.IAsyncResult BeginGetData2(System.AsyncCallback callback, object asyncState);
        
        int EndGetData2(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncWorkerService/GetData3", ReplyAction="http://tempuri.org/IAsyncWorkerService/GetData3Response")]
        int GetData3();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAsyncWorkerService/GetData3", ReplyAction="http://tempuri.org/IAsyncWorkerService/GetData3Response")]
        System.IAsyncResult BeginGetData3(System.AsyncCallback callback, object asyncState);
        
        int EndGetData3(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsyncWorkerServiceChannel : RxAsyncConsole.AsyncWorkerServiceReference.IAsyncWorkerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetData1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetData1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetData2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetData2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetData3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetData3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsyncWorkerServiceClient : System.ServiceModel.ClientBase<RxAsyncConsole.AsyncWorkerServiceReference.IAsyncWorkerService>, RxAsyncConsole.AsyncWorkerServiceReference.IAsyncWorkerService {
        
        private BeginOperationDelegate onBeginGetData1Delegate;
        
        private EndOperationDelegate onEndGetData1Delegate;
        
        private System.Threading.SendOrPostCallback onGetData1CompletedDelegate;
        
        private BeginOperationDelegate onBeginGetData2Delegate;
        
        private EndOperationDelegate onEndGetData2Delegate;
        
        private System.Threading.SendOrPostCallback onGetData2CompletedDelegate;
        
        private BeginOperationDelegate onBeginGetData3Delegate;
        
        private EndOperationDelegate onEndGetData3Delegate;
        
        private System.Threading.SendOrPostCallback onGetData3CompletedDelegate;
        
        public AsyncWorkerServiceClient() {
        }
        
        public AsyncWorkerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsyncWorkerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsyncWorkerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsyncWorkerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetData1CompletedEventArgs> GetData1Completed;
        
        public event System.EventHandler<GetData2CompletedEventArgs> GetData2Completed;
        
        public event System.EventHandler<GetData3CompletedEventArgs> GetData3Completed;
        
        public int GetData1() {
            return base.Channel.GetData1();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetData1(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData1(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndGetData1(System.IAsyncResult result) {
            return base.Channel.EndGetData1(result);
        }
        
        private System.IAsyncResult OnBeginGetData1(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetData1(callback, asyncState);
        }
        
        private object[] OnEndGetData1(System.IAsyncResult result) {
            int retVal = this.EndGetData1(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetData1Completed(object state) {
            if ((this.GetData1Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetData1Completed(this, new GetData1CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetData1Async() {
            this.GetData1Async(null);
        }
        
        public void GetData1Async(object userState) {
            if ((this.onBeginGetData1Delegate == null)) {
                this.onBeginGetData1Delegate = new BeginOperationDelegate(this.OnBeginGetData1);
            }
            if ((this.onEndGetData1Delegate == null)) {
                this.onEndGetData1Delegate = new EndOperationDelegate(this.OnEndGetData1);
            }
            if ((this.onGetData1CompletedDelegate == null)) {
                this.onGetData1CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetData1Completed);
            }
            base.InvokeAsync(this.onBeginGetData1Delegate, null, this.onEndGetData1Delegate, this.onGetData1CompletedDelegate, userState);
        }
        
        public int GetData2() {
            return base.Channel.GetData2();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetData2(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData2(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndGetData2(System.IAsyncResult result) {
            return base.Channel.EndGetData2(result);
        }
        
        private System.IAsyncResult OnBeginGetData2(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetData2(callback, asyncState);
        }
        
        private object[] OnEndGetData2(System.IAsyncResult result) {
            int retVal = this.EndGetData2(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetData2Completed(object state) {
            if ((this.GetData2Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetData2Completed(this, new GetData2CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetData2Async() {
            this.GetData2Async(null);
        }
        
        public void GetData2Async(object userState) {
            if ((this.onBeginGetData2Delegate == null)) {
                this.onBeginGetData2Delegate = new BeginOperationDelegate(this.OnBeginGetData2);
            }
            if ((this.onEndGetData2Delegate == null)) {
                this.onEndGetData2Delegate = new EndOperationDelegate(this.OnEndGetData2);
            }
            if ((this.onGetData2CompletedDelegate == null)) {
                this.onGetData2CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetData2Completed);
            }
            base.InvokeAsync(this.onBeginGetData2Delegate, null, this.onEndGetData2Delegate, this.onGetData2CompletedDelegate, userState);
        }
        
        public int GetData3() {
            return base.Channel.GetData3();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetData3(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData3(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndGetData3(System.IAsyncResult result) {
            return base.Channel.EndGetData3(result);
        }
        
        private System.IAsyncResult OnBeginGetData3(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetData3(callback, asyncState);
        }
        
        private object[] OnEndGetData3(System.IAsyncResult result) {
            int retVal = this.EndGetData3(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetData3Completed(object state) {
            if ((this.GetData3Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetData3Completed(this, new GetData3CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetData3Async() {
            this.GetData3Async(null);
        }
        
        public void GetData3Async(object userState) {
            if ((this.onBeginGetData3Delegate == null)) {
                this.onBeginGetData3Delegate = new BeginOperationDelegate(this.OnBeginGetData3);
            }
            if ((this.onEndGetData3Delegate == null)) {
                this.onEndGetData3Delegate = new EndOperationDelegate(this.OnEndGetData3);
            }
            if ((this.onGetData3CompletedDelegate == null)) {
                this.onGetData3CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetData3Completed);
            }
            base.InvokeAsync(this.onBeginGetData3Delegate, null, this.onEndGetData3Delegate, this.onGetData3CompletedDelegate, userState);
        }
    }
}
