//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RxAsyncConsole.WorkerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkerServiceReference.IWorkerService")]
    public interface IWorkerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkerService/GetDataLongWay", ReplyAction="http://tempuri.org/IWorkerService/GetDataLongWayResponse")]
        int GetDataLongWay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkerService/GetData1", ReplyAction="http://tempuri.org/IWorkerService/GetData1Response")]
        int GetData1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkerService/GetData2", ReplyAction="http://tempuri.org/IWorkerService/GetData2Response")]
        int GetData2();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkerServiceChannel : RxAsyncConsole.WorkerServiceReference.IWorkerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkerServiceClient : System.ServiceModel.ClientBase<RxAsyncConsole.WorkerServiceReference.IWorkerService>, RxAsyncConsole.WorkerServiceReference.IWorkerService {
        
        public WorkerServiceClient() {
        }
        
        public WorkerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetDataLongWay() {
            return base.Channel.GetDataLongWay();
        }
        
        public int GetData1() {
            return base.Channel.GetData1();
        }
        
        public int GetData2() {
            return base.Channel.GetData2();
        }
    }
}
